export const languageFlags = {
  albanian: '🇦🇱',
  amharic: '🇪🇹',
  arabic: '🇸🇦',
  armenian: '🇦🇲',
  'bahasa-indonesia': '🇮🇩',
  'bahasa-melayu': '🇲🇾',
  bulgarian: '🇧🇬',
  catalan: '🇪🇸',
  chinese: '🇨🇳',
  croatian: '🇭🇷',
  czech: '🇨🇿',
  danish: '🇩🇰',
  dutch: '🇳🇱',
  english: '🇬🇧',
  estonian: '🇪🇪',
  finnish: '🇫🇮',
  french: '🇫🇷',
  german: '🇩🇪',
  greek: '🇬🇷',
  hebrew: '🇮🇱',
  hindi: '🇮🇳',
  hungarian: '🇭🇺',
  indonesian: '🇮🇩',
  italian: '🇮🇹',
  japanese: '🇯🇵',
  kazakh: '🇰🇿',
  kinyarwanda: '🇷🇼',
  korean: '🇰🇷',
  latvian: '🇱🇻',
  lithuanian: '🇱🇹',
  macedonian: '🇲🇰',
  malay: '🇲🇾',
  nigerian: '🇳🇬',
  norwegian: '🇳🇴',
  polish: '🇵🇱',
  portuguese: '🇵🇹',
  romanian: '🇷🇴',
  russian: '🇷🇺',
  serbian: '🇷🇸',
  sinhala: '🇱🇰',
  slovak: '🇸🇰',
  slovenian: '🇸🇮',
  spanish: '🇪🇸',
  swedish: '🇸🇪',
  tagalog: '🇵🇭',
  tamil: '🇮🇳',
  thai: '🇹🇭',
  turkish: '🇹🇷',
  ukrainian: '🇺🇦',
  vietnamese: '🇻🇳',
};

export const isLanguageFlag = (tag) =>
  typeof tag === 'object' && tag.key === 'language' && Boolean(languageFlags[tag.value]);

// Language flags go after the other tags, keeping the order within each group.
export const orderTagsForDisplay = (tags) => [
  ...tags.filter((tag) => !isLanguageFlag(tag)),
  ...tags.filter((tag) => isLanguageFlag(tag)),
];
