name: ClusterFuzzLite batch fuzzing
on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions: read-all

jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: javascript
          sanitizer: address

      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: batch
          sanitizer: address
