name: Deploy GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  
jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - working-directory: page
        run: npm ci
      - name: Parse Markdowns
        working-directory: tools
        run: |
          npm ci
          node mdValidator.js
          node mdParser.js
          node generateIcs.js
          node generateIcs4OpenedCfps.js
          node generateRSS.js
          node geoCodes.js
      - name: Run Tests
        working-directory: page
        run: npm test -- --run
      - working-directory: page
        run: npm run build
      - name: Make all-*.json files available at the site root
        working-directory: tools
        run: |
          mv ../page/src/misc/all-events.json ../page/build/all-events.json
          mv ../page/src/misc/all-cfps.json ../page/build/all-cfps.json
          mv ../page/src/misc/*.ics ../page/build/
          mv ../page/src/misc/feed-events.* ../page/build/
          mv ../page/src/misc/og-preview.png ../page/build/
      - name: Deploy to GitHub Pages
        if: github.ref_name == 'main'
        uses: crazy-max/ghaction-github-pages@v5 # v5
        with:
          target_branch: gh-pages
          build_dir: page/build/
          keep_history: true
          fqdn: developers.events # CNAME
          jekyll: false # Solve website 404
          allow_empty_commit: true # will help handle scenarios where multiple workflows push concurrently by allowing the action to complete even if there are no actual changes to commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
